In [14]:
# Implementation of UNSGA III with dtlz1, dtlz2, dtlz3, zdt4, zdt6 and nsga iii with zdt5, zdt6
# Implementation of RNSGA III and MOEA/D with dtlz1,  dtlz2, dtlz3, zdt4, zdt6

In [109]:
!pip install pymoo
from pymoo.algorithms.moo.nsga3 import NSGA3
from pymoo.algorithms.moo.unsga3 import UNSGA3
from pymoo.algorithms.moo.rnsga3 import RNSGA3
from pymoo.algorithms.moo.moead import MOEAD
from pymoo.problems import get_problem
from pymoo.optimize import minimize
from pymoo.util.ref_dirs import get_reference_directions
import numpy as np

!pip install pygmo
from pygmo import hypervolume

In [143]:
problem = get_problem("dtlz3", n_var=3)

# create the reference directions to be used for the optimization - just a single one here
#ref_dirs = np.array([[1.0, 1.0]]) # R/U/NSGA III,
ref_dirs = get_reference_directions("uniform", 3, n_partitions=12)

# create the algorithm object,
algorithm = MOEAD(ref_dirs,
    n_neighbors=15,
    prob_neighbor_mating=0.3,)

# execute the optimization
res = minimize(problem,
               algorithm,
               termination=('n_gen', 150),
               seed=1)

print("UNSGA3: Best solution found: \nX = %s\nF = %s" % (res.X, res.F))

UNSGA3: Best solution found: 
X = [[9.99486128e-01 3.82061804e-01 4.99940923e-01]
 [9.41988118e-01 9.91111901e-01 4.99985665e-01]
 [8.74810795e-01 9.98336102e-01 4.99953788e-01]
 [7.97323292e-01 9.99108209e-01 4.99988151e-01]
 [7.04665736e-01 9.97076218e-01 4.99988122e-01]
 [6.03435206e-01 9.98427638e-01 4.99986623e-01]
 [5.02413178e-01 9.98806512e-01 4.99934797e-01]
 [3.94002706e-01 9.97242362e-01 4.99988936e-01]
 [2.91043195e-01 9.98472975e-01 4.99995423e-01]
 [2.19427314e-01 9.96407354e-01 4.99985581e-01]
 [1.07426627e-01 9.99914867e-01 4.99954960e-01]
 [5.30240914e-02 9.91845394e-01 4.99953690e-01]
 [7.02628515e-04 9.99599837e-01 4.99989851e-01]
 [9.41988118e-01 2.17515466e-02 4.99987418e-01]
 [9.11227333e-01 4.79073644e-01 4.99988139e-01]
 [8.45346171e-01 7.01935379e-01 4.99986602e-01]
 [7.61431295e-01 7.91970536e-01 4.99987525e-01]
 [6.68431227e-01 8.34725976e-01 4.99988049e-01]
 [5.46223304e-01 8.75996368e-01 4.99985727e-01]
 [4.31619031e-01 8.89077738e-01 4.99955093e-01]
 [3.25

In [147]:
pareto = res.F

In [148]:
ref = [[1,1,1],
       [1.5,1.5,2],
       [2,2,2],
       [2.5,2.5,2.5],
       [3,1,1.5],
       [2.3,4.1,1.2],
       [5,5,5],
       [8.5,7.3,8.5],
       [9.1,15.2,3.2],
       [10,10,10]]

In [149]:
hv = hypervolume(pareto)
for i in ref:
  print(hv.compute(i))

ValueError: 
function: assert_minimisation
where: /root/install/pagmo2-2.19.0/src/utils/hv_algos/hv_algorithm.cpp, 256
what: Reference point is invalid: another point seems to be outside the reference point boundary, or be equal to it:
 P[0]	= (0.000667, 0.000456, 1.000689)
 R	= (1.000000, 1.000000, 1.000000)



In [135]:
[j.pop(2) for j in ref]
ref

[[1, 1],
 [1.5, 1.5],
 [2, 2],
 [2.5, 2.5],
 [3, 1],
 [2.3, 4.1],
 [5, 5],
 [8.5, 7.3],
 [9.1, 15.2],
 [10, 10]]

In [99]:
from pymoo.operators.selection.tournament import TournamentSelection
from pymoo.operators.crossover.sbx import SBX

In [ ]:
t = Tou